- name: copy systemd unit
  ansible.builtin.template:
    src: dozzle.service.j2
    dest: /etc/systemd/system/dozzle.service
    owner: root
    group: root
    mode: "644"
  notify: restart dozzle.service

- name: create /data/dozzle dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart dozzle.service

- name: copy users.yml file
  ansible.builtin.template:
    src: users.yml.j2
    dest: "{{ root }}/users.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart dozzle.service

- name: start dozzle.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: dozzle.service
  register: dozzle_started
