---
- name: Merge user lists
  ansible.builtin.set_fact:
    merged_users: "{{ users | default([]) + (hostvars[inventory_hostname]['extra_users'] | default([])) }}"

- name: Ensure all standard groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ default_user_groups }}"

- name: Ensure passwordless sudo for sudo group
  ansible.builtin.template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/sudo"
    mode: '0440'


- name: Create users and install ssh keys
  ansible.builtin.include_tasks: users.yml
