- name: copy systemd unit
  ansible.builtin.template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: "644"
  notify: restart nginx.service

- name: create /data/nginx dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart nginx.service

- name: start nginx.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: nginx.service
  register: nginx_started
