# Muss vor dem Start existieren, legt {{ root }} gleich mit an.
- name: create {{ root }}/data dir
  ansible.builtin.file:
    path: "{{ root }}/data"
    state: directory
    mode: '755'

- name: Deploy {{ role_name }}
  ansible.builtin.import_tasks: docker-compose-service.yml
