- name: copy systemd unit
  ansible.builtin.template:
    src: minecraft_java.service.j2
    dest: /etc/systemd/system/minecraft_java.service
    owner: root
    group: root
    mode: "644"
  notify: restart minecraft_java.service

- name: create {{ root }} dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: create {{ root }}/data dir
  ansible.builtin.file:
    path: "{{ root }}/data"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart minecraft_java.service

- name: start minecraft_java.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: minecraft_java.service
  register: minecraft_java_started
