- name: copy systemd unit
  ansible.builtin.template:
    src: grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    owner: root
    group: root
    mode: "644"
  notify: restart grafana.service

- name: create /data/grafana dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: Copy templates
  ansible.builtin.import_tasks: copy-all-templates.yml
  vars:
    directory: ../templates
    notify: restart grafana.service

- name: Create docker network grafana
  community.general.docker_network:
    name: grafana

- name: start grafana.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: grafana.service
  register: grafana_started
