---

- hosts: tyrion
  become: true
  roles:
    - role: docker
      tags: docker
    - role: ntp_server
      tags:
        - ntp_server
        - container
    - role: traefik
      tags:
        - traefik
        - container
    - role: docker_socket_proxy
      tags:
        - dockersocketproxy
        - container
    - role: crowdsec
      tags:
        - crowdsec
        - container
    - role: whats-up-docker
      tags:
        - whatsupdocker
        - container
    - role: dozzle
      tags:
        - dozzle
        - container
    - role: pihole
      tags:
        - pihole
        - container
    - role: pihole-orbital-sync
      tags:
        - pihole
        - container
    - role: homepage-dashboard
      tags:
        - homepage
        - container
    - role: vaultwarden
      tags:
        - vaultwarden
        - container
    - role: homebridge
      tags:
        - homebridge
        - container
    - role: homeassistant
      tags:
        - homeassistant
        - container
    - role: plex
      tags:
        - plex
        - container
    - role: tautulli
      tags:
        - tautulli
        - container
    - role: overseerr
      tags:
        - overseerr
        - container
    - role: ganymede
      tags:
        - ganymede
        - container
    - role: spotify_tracker
      tags:
        - spotify
        - spotify_tracker
        - container
    - role: it-tools
      tags:
        - it-tools
        - container
    - role: cyberchef
      tags:
        - cyberchef
        - container
    - role: convertx
      tags:
        - convertx
        - container
    - role: pairdrop
      tags:
        - pairdrop
        - container
    - role: stirling-pdf
      tags:
        - pdf
        - container
    - role: openspeedtest
      tags:
        - openspeedtest
        - container
    - role: speedtest-tracker
      tags:
        - speedtest-tracker
        - container
    - role: grafana
      tags:
        - grafana
        - container
    - role: prometheus
      tags:
        - prometheus
        - container
    - role: wallos
      tags:
        - wallos
        - container
    - role: crafty
      tags:
        - crafty
        - container
    - role: uptimekuma
      tags:
        - uptimekuma
        - container
