---

- hosts: tyrion
  become: true

  tasks:
    - name: Set timezone to Europe/Berlin
      community.general.timezone:
        name: Europe/Berlin

  roles:
    - role: docker
      tags: docker
    - role: traefik
      tags:
        - traefik
    - role: docker_socket_proxy
      tags:
        - dockersocketproxy
    - role: crowdsec
      tags:
        - crowdsec
    - role: whats-up-docker
      tags:
        - whatsupdocker
    - role: dozzle
      tags:
        - dozzle
    - role: pihole
      tags:
        - pihole
    - role: pihole-orbital-sync
      tags:
        - pihole
    - role: homepage
      tags:
        - homepage
    - role: vaultwarden
      tags:
        - vaultwarden
    - role: plex
      tags:
        - plex
    - role: tautulli
      tags:
        - tautulli
    - role: overseerr
      tags:
        - overseerr
    - role: ganymede
      tags:
        - ganymede
    - role: spotify_tracker
      tags:
        - spotify
        - spotify_tracker
    - role: spotizerr
      tags:
        - spotify
        - spotizerr
    - role: it-tools
      tags:
        - it-tools
    - role: cyberchef
      tags:
        - cyberchef
    - role: convertx
      tags:
        - convertx
    - role: pairdrop
      tags:
        - pairdrop
    - role: stirling-pdf
      tags:
        - pdf
    - role: openspeedtest
      tags:
        - openspeedtest
    - role: speedtest-tracker
      tags:
        - speedtest-tracker
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: wallos
      tags:
        - wallos
    - role: crafty
      tags:
        - crafty
    - role: uptimekuma
      tags:
        - uptimekuma
    - role: excalidraw
      tags:
        - excalidraw
    - role: docmost
      tags:
        - docmost
    - role: scribblers
      tags:
        - scribblers
    - role: cobaltdownloader
      tags:
        - cobaltdownloader
    - role: teamspeak
      tags:
        - teamspeak
