---

- hosts: drogon
  become: true
  roles:
    - role: docker
      tags: docker
    - role: traefik_httpchallenge
      tags:
        - traefik
        - container
    - role: vaultwarden
      tags:
        - vaultwarden
        - container
    - role: teamspeak
      tags:
        - teamspeak
        - container
    - role: wordpress_nl
      tags:
        - wordpress_nl
        - wordpress
        - container
    - role: wordpress_mfw
      tags:
        - wordpress_mfw
        - wordpress
        - container
    - role: webserver
      tags:
        - webserver
        - container
    - role: mailserver
      tags:
        - mailserver
        - container
        - mail
    - role: roundcubemail
      tags:
        - roundcubemail
        - container
        - mail
    - role: portainer
      tags:
        - portainer
        - container
    - role: littlelink
      tags:
        - littlelink
        - container
    - role: minecraft_java
      tags:
        - minecraft_java
        - container