---

- hosts: tyrion
  become: true
  roles:
    - role: docker
      tags: docker
    - role: traefik
      tags:
        - traefik
        - container
    - role: homepage-dashboard
      tags:
        - homepage
        - container
    - role: homebridge
      tags:
        - homebridge
        - container
    - role: plex
      tags:
        - plex
        - container
    - role: tautulli
      tags:
        - tautulli
        - container
    - role: overseerr
      tags:
        - overseerr
        - container
    - role: minecraft_bedrock
      tags:
        - minecraft_bedrock
        - container
    - role: minecraft_java
      tags:
        - minecraft_java
        - container
    - role: spotify_tracker
      tags:
        - spotify
        - spotify_tracker
        - container
    - role: it-tools
      tags:
        - it-tools
        - container
