---

- hosts: drogon
  become: true
  roles:
    - role: docker
      tags: docker
    - role: traefik_httpchallenge
      tags:
        - traefik
        - container
    - role: whats-up-docker
      tags:
        - whatsupdocker
        - container
    - role: wordpress_mfw
      tags:
        - wordpress_mfw
        - wordpress
        - container
    - role: webserver
      tags:
        - webserver
        - container
    - role: littlelink
      tags:
        - littlelink
        - container
    - role: minecraft_java
      tags:
        - minecraft_java
        - container
    - role: uptimekuma
      tags:
        - uptimekuma
        - container