---

- hosts: tyrion
  become: true
  roles:
    - name: nic_configuration_tyrion
      tags: nic_configuration_tyrion
    - name: docker
      tags: docker
    - name: nginx
      tags: nginx
    - name: portainer
      tags: portainer
    - name: heimdall
      tags: heimdall
    - name: homebridge
      tags: homebridge
    - name: openspeedtest
      tags: openspeedtest
    - name: smokeping
      tags: smokeping