---

- hosts: drogon
  become: true

  roles:
# System Roles
    - role: system_config
      tags:
        - system
      vars:
        enable_auto_updates: true
        security_only_updates: true
    - role: admin_users
      tags:
        - system
    - role: ssh_hardening
      tags:
        - system
      vars:
        sshd_allow_users: ["nils"]

# Docker Roles
    - role: docker
      tags: docker
    - role: traefik_httpchallenge
      tags:
        - traefik
    - role: docker_socket_proxy
      tags:
        - dockersocketproxy
    - role: crowdsec
      tags:
        - crowdsec
    - role: whats-up-docker
      tags:
        - whatsupdocker
    - role: dozzle
      tags:
        - dozzle
    - role: wordpress_mfw
      tags:
        - wordpress_mfw
        - wordpress
    - role: webserver
      tags:
        - webserver
    - role: littlelink
      tags:
        - littlelink
    - role: uptimekuma
      tags:
        - uptimekuma
    - role: teamspeak
      tags:
        - teamspeak
