---

- hosts: tyrion
  become: true
  roles:
    - name: nic_configuration_tyrion
      tags: nic_configuration_tyrion
    - name: docker
      tags: docker
    - name: traefik
      tags:
        - traefik
        - container
    - name: portainer
      tags:
        - portainer
        - container
    - name: pihole
      tags:
        - pihole
        - container
    - name: heimdall
      tags:
        - heimdall
        - container
    - name: homebridge
      tags:
        - homebridge
        - container
    - name: openspeedtest
      tags:
        - openspeedtest
        - container
    - name: smokeping
      tags:
        - smokeping
        - container
    - name: plex
      tags:
        - plex
        - container
    - name: tautulli
      tags:
        - tautulli
        - container
    - name: it-tools
      tags:
        - it-tools
        - container