---

- hosts: tyrion
  become: true
  roles:
    - role: nic_configuration_tyrion
      tags: nic_configuration_tyrion
    - role: docker
      tags: docker
    - role: traefik
      tags:
        - traefik
        - container
    - role: portainer
      tags:
        - portainer
        - container
    - role: pihole
      tags:
        - pihole
        - container
    - role: heimdall
      tags:
        - heimdall
        - container
    - role: homebridge
      tags:
        - homebridge
        - container
    - role: openspeedtest
      tags:
        - openspeedtest
        - container
    - role: plex
      tags:
        - plex
        - container
    - role: tautulli
      tags:
        - tautulli
        - container
    - role: it-tools
      tags:
        - it-tools
        - container
    - role: minecraft_bedrock
      tags:
        - minecraft_bedrock
        - container
    - role: minecraft_java
      tags:
        - minecraft_java
        - container
    - role: uptimekuma
      tags:
        - uptimekuma
        - container