---

- hosts: drogon
  become: true
  roles:
    - name: docker
      tags: docker
    - name: traefik_httpchallenge
      tags:
        - traefik
        - container
    - name: teamspeak
      tags:
        - teamspeak
        - container
    - name: wordpress_nl
      tags:
        - wordpress_nl
        - wordpress
        - container