---

- hosts: brandon
  become: true
  roles:
    - role: docker
      tags: docker
    - role: traefik
      tags:
        - traefik
        - container
    - role: pihole
      tags:
        - pihole
        - container
    - role: homebridge
      tags:
        - homebridge
        - container
