---

- hosts: tyrion
  become: true

  roles:
# System Roles
    - role: system_config
      tags:
        - system
      vars:
        enable_auto_updates: true
        security_only_updates: true
    - role: admin_users
      tags:
        - system
    - role: ssh_hardening
      tags:
        - system
      vars:
        sshd_allow_users: ["nils"]

# Docker Roles
    - role: docker
      tags: docker
    - role: traefik
      tags:
        - traefik
    - role: docker_socket_proxy
      tags:
        - dockersocketproxy
    - role: crowdsec
      tags:
        - crowdsec
    - role: whats-up-docker
      tags:
        - whatsupdocker
    - role: dozzle
      tags:
        - dozzle
    - role: homepage
      tags:
        - homepage
    - role: vaultwarden
      tags:
        - vaultwarden
    - role: paperlessngx
      tags:
        - paperlessngx
    - role: plex
      tags:
        - plex
    - role: tautulli
      tags:
        - tautulli
    - role: seerr
      tags:
        - seerr
    - role: ganymede
      tags:
        - ganymede
    - role: spotify_tracker
      tags:
        - spotify
        - spotify_tracker
    - role: spotizerr
      tags:
        - spotify
        - spotizerr
    - role: it-tools
      tags:
        - it-tools
    - role: networking-toolbox
      tags:
        - networking-toolbox
    - role: cyberchef
      tags:
        - cyberchef
    - role: convertx
      tags:
        - convertx
    - role: pairdrop
      tags:
        - pairdrop
    - role: stirling-pdf
      tags:
        - pdf
    - role: openspeedtest
      tags:
        - openspeedtest
    - role: speedtest-tracker
      tags:
        - speedtest-tracker
    - role: grafana
      tags:
        - grafana
    - role: prometheus
      tags:
        - prometheus
    - role: wallos
      tags:
        - wallos
    - role: crafty
      tags:
        - crafty
    - role: excalidraw
      tags:
        - excalidraw
    - role: docmost
      tags:
        - docmost
    - role: scribblers
      tags:
        - scribblers
    - role: cobaltdownloader
      tags:
        - cobaltdownloader
