---

- hosts: drogon
  become: true
  roles:
    - name: docker
      tags: docker
    - name: traefik_httpchallenge
      tags:
        - traefik
        - container
    - name: vaultwarden
      tags:
        - vaultwarden
        - container
    - name: teamspeak
      tags:
        - teamspeak
        - container
    - name: wordpress_nl
      tags:
        - wordpress_nl
        - wordpress
        - container
    - name: wordpress_mfw
      tags:
        - wordpress_mfw
        - wordpress
        - container
    - name: webserver
      tags:
        - webserver
        - container
    - name: docker-mailserver
      tags:
        - docker-mailserver
        - container
    - name: portainer
      tags:
        - portainer
        - container
    - name: littlelink
      tags:
        - littlelink
        - container
    - name: roundcubemail
      tags:
        - roundcubemail
        - container