roles:
  - name: geerlingguy.docker
    version: 6.0.4
  - name: geerlingguy.pip
    version: 2.2.0
  - name: community.docker

collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker