- name: copy systemd unit
  ansible.builtin.template:
    src: mailserver.service.j2
    dest: /etc/systemd/system/mailserver.service
    owner: root
    group: root
    mode: "644"
  notify: restart mailserver.service

- name: create {{ root }} dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: create {{ root }}/config/ dir
  ansible.builtin.file:
    path: "{{ root }}/config/"
    state: directory


- name: copy docker-compose file with cert companion
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  when: mx_use_webmail == "no"
  notify: restart mailserver.service

- name: copy docker-compose file with out cert companion
  ansible.builtin.template:
    src: docker-compose-without-certcompanion.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  when: mx_use_webmail == "yes"
  notify: restart mailserver.service


- name: copy mailserver env file
  ansible.builtin.template:
    src: mailserver.env.j2
    dest: "{{ root }}/mailserver.env"
    owner: root
    group: root
    mode: "644"
  notify: restart mailserver.service

- name: copy fail2ban config file
  ansible.builtin.template:
    src: config/fail2ban-fail2ban.cf.j2
    dest: "{{ root }}/config/fail2ban-fail2ban.cf"
    owner: root
    group: root
    mode: "644"
  notify: restart mailserver.service

- name: copy fail2ban jail config file
  ansible.builtin.template:
    src: config/fail2ban-jail.cf.j2
    dest: "{{ root }}/config/fail2ban-jail.cf"
    owner: root
    group: root
    mode: "644"
  notify: restart mailserver.service

- name: Download mailserver setup script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/docker-mailserver/docker-mailserver/master/setup.sh
    dest: "{{ root }}/setup.sh"
    mode: '744'

- name: Copy Traefik Cert file with different permissions
  ansible.builtin.copy:
    src: "/data/traefik/conf/acme/le.json"
    dest: "{{ root }}/le.json"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- name: start mailserver.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: mailserver.service
  register: mailserver_started
