- name: copy systemd unit
  ansible.builtin.template:
    src: pihole-orbital-sync.service.j2
    dest: /etc/systemd/system/pihole-orbital-sync.service
    owner: root
    group: root
    mode: "644"
  notify: restart pihole-orbital-sync.service

- name: create /data/pihole-orbital-sync dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart pihole-orbital-sync.service

- name: start pihole-orbital-sync.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: pihole-orbital-sync.service
  register: pihole_orbital_sync_started