- name: copy systemd unit
  ansible.builtin.template:
    src: cyberchef.service.j2
    dest: /etc/systemd/system/cyberchef.service
    owner: root
    group: root
    mode: "644"
  notify: restart cyberchef.service

- name: create /data/cyberchef dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart cyberchef.service

- name: start cyberchef.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: cyberchef.service
  register: cyberchef_started
