- name: Update repositories cache and install "nfs-common" package
  ansible.builtin.apt:
    name: nfs-common
    update_cache: yes

- name: copy systemd unit
  ansible.builtin.template:
    src: "{{ role_name }}.service.j2"
    dest: /etc/systemd/system/{{ role_name }}.service
    owner: root
    group: root
    mode: "666"
  notify: restart {{ role_name }}.service

- name: create /data/{{ role_name }} dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy mount file for {{ role_name }}_media volume
  ansible.builtin.template:
    src: data-{{ role_name }}-media.mount.j2
    dest: "/etc/systemd/system/data-{{ role_name }}-media.mount"
    owner: root
    group: root
    mode: "666"
  notify: restart data-{{ role_name }}-media.mount

- name: start data-{{ role_name }}-media.mount
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: data-{{ role_name }}-media.mount
  register: ganymede_media_started

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "666"
  notify: restart {{ role_name }}.service

- name: start {{ role_name }}.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: "{{ role_name }}.service"
  register: ganymede_started
