- name: restart plex.service
  ansible.builtin.systemd:
    name: plex.service
    state: restarted
    daemon_reload: true


- name: restart data-plex-media.mount
  when: plexmedia_started is not changed
  ansible.builtin.systemd:
    name: data-plex-media.mount
    state: restarted


- name: update initramfs
  ansible.builtin.command: sudo update-initramfs -u
  changed_when: true
