- name: restart plex.service
  when: plex_started is not changed
  ansible.builtin.systemd:
    name: plex.service
    state: restarted


- name: restart data-plex-media.mount
  when: plexmedia_started is not changed
  ansible.builtin.systemd:
    name: data-plex-media.mount
    state: restarted


- name: update initramfs
  ansible.builtin.command: sudo update-initramfs -u