- name: check mountpoint exist
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Mount network share
  ansible.posix.mount:
    src: "{{ uri }}"
    path: "{{ mountpoint }}"
    fstype: btrfs
    opts: 'username={{ username }},password={{ password }}'
    state: mounted

# - name: copy systemd unit
#   ansible.builtin.template:
#     src: plex.service.j2
#     dest: /etc/systemd/system/plex.service
#     owner: root
#     group: root
#     mode: "644"
#   notify: restart plex.service

# - name: create /data/plex dir
#   ansible.builtin.file:
#     path: "{{ root }}"
#     state: directory

# - name: copy docker-compose file
#   ansible.builtin.template:
#     src: docker-compose.yml.j2
#     dest: "{{ root }}/docker-compose.yml"
#     owner: root
#     group: root
#     mode: "644"
#   notify: restart plex.service

# - name: start plex.service
#   ansible.builtin.systemd:
#     state: started
#     daemon_reload: true
#     enabled: true
#     name: plex.service
#   register: plex_started
