- name: copy systemd unit
  ansible.builtin.template:
    src: heimdall.service.j2
    dest: /etc/systemd/system/heimdall.service
    owner: root
    group: root
    mode: "644"
  notify: restart heimdall.service

- name: create /data/heimdall dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: Return internal pihole ip to temp var
  ansible.builtin.command: "docker exec pihole dig +short pihole"
  register: raw_pihole_ip
  when: heimdall_dns == "pihole"

- set_fact:
    heimdall_dns: "{{ raw_pihole_ip.stdout }}"
  when: heimdall_dns == "pihole"

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart heimdall.service

- name: start heimdall.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: heimdall.service
  register: heimdall_started
