traefik:
  nils:
    hash: "{{ vault_traefik_nils_hash }}"
    username: "{{ vault_traefik_nils_username }}"
    password: "{{ vault_traefik_nils_password }}"
  other:
    hash: "{{ vault_traefik_other_hash }}"
    username: "{{ vault_traefik_other_username }}"
    password: "{{ vault_traefik_other_password }}"
