- name: copy systemd unit
  ansible.builtin.template:
    src: smokeping.service.j2
    dest: /etc/systemd/system/smokeping.service
    owner: root
    group: root
    mode: "644"
  notify: restart smokeping.service

- name: create /data/smokeping dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: create /data/smokeping/config dir
  ansible.builtin.file:
    path: "{{ root }}/config"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart smokeping.service

- name: copy Targets file
  ansible.builtin.template:
    src: Targets.j2
    dest: "{{ root }}/config/Targets"
    owner: root
    group: root
    mode: "644"
  notify: restart smokeping.service

- name: start smokeping.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: smokeping.service
  register: smokeping_started
