- name: copy systemd unit
  ansible.builtin.template:
    src: teamspeak.service.j2
    dest: /etc/systemd/system/teamspeak.service
    owner: root
    group: root
    mode: "644"
  notify: restart teamspeak.service

- name: create /data/teamspeak dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart teamspeak.service

- name: start teamspeak.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: teamspeak.service
  register: teamspeak_started
