- name: copy systemd unit
  ansible.builtin.template:
    src: homebridge.service.j2
    dest: /etc/systemd/system/homebridge.service
    owner: root
    group: root
    mode: "644"
  notify: restart homebridge.service

- name: create /data/homebridge dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart homebridge.service

- name: start homebridge.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: homebridge.service
  register: homebridge_started
