- name: copy systemd unit
  ansible.builtin.template:
    src: spotify_tracker.service.j2
    dest: /etc/systemd/system/spotify_tracker.service
    owner: root
    group: root
    mode: "644"
  notify: restart spotify_tracker.service

- name: create /data/spotify_tracker dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart spotify_tracker.service

- name: start spotify_tracker.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: spotify_tracker.service
  register: spotify_tracker_started
