ganymede_domain: ganymede.home-lorenzen.de
ganymede_twitch_client_id: "{{ vault_ganymede_twitch_client_id }}"
ganymede_twitch_client_secret: "{{ vault_ganymede_twitch_client_secret }}"
ganymede_db_password: "{{ vault_ganymede_db_password }}"
