- name: Copy templates
  ansible.builtin.import_tasks: copy-all-templates.yml
  vars:
    directory: ../templates
    notify: restart unifi.service

- name: copy systemd unit
  ansible.builtin.template:
    src: unifi.service.j2
    dest: /etc/systemd/system/unifi.service
    owner: root
    group: root
    mode: "644"
  notify: restart unifi.service

- name: start unifi.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: unifi.service
  register: unifi_started
