- name: copy systemd unit
  ansible.builtin.template:
    src: portainer.service.j2
    dest: /etc/systemd/system/portainer.service
    owner: root
    group: root
    mode: "644"
  notify: restart portainer.service

- name: create /data/portainer dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart portainer.service

- name: start portainer.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: portainer.service
  register: portainer_started
