
- name: copy eth0 config used for management
  ansible.builtin.template:
    src: eth0.network.j2
    dest: /etc/systemd/network/eth0.network
    owner: root
    group: systemd-network
    mode: "640"
  notify: restart systemd-networkd
