- name: copy systemd unit
  ansible.builtin.template:
    src: roundcubemail.service.j2
    dest: /etc/systemd/system/roundcubemail.service
    owner: root
    group: root
    mode: "644"
  notify: restart roundcubemail.service

- set_fact:
    roundcubemail_domain: "{{ mx_domain }}"
  when: mx_use_webmail == "yes"

- name: create /data/roundcubemail dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart roundcubemail.service

- name: start roundcubemail.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: roundcubemail.service
  register: roundcubemail_started

