- name: copy systemd unit
  ansible.builtin.template:
    src: openspeedtest.service.j2
    dest: /etc/systemd/system/openspeedtest.service
    owner: root
    group: root
    mode: "644"
  notify: restart openspeedtest.service

- name: create /data/openspeedtest dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart openspeedtest.service

- name: start openspeedtest.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: openspeedtest.service
  register: openspeedtest_started
