- name: copy systemd unit
  ansible.builtin.template:
    src: uptimekuma.service.j2
    dest: /etc/systemd/system/uptimekuma.service
    owner: root
    group: root
    mode: "644"
  notify: restart uptimekuma.service

- name: create /data/uptimekuma dir
  ansible.builtin.file:
    path: "{{ root }}"
    state: directory

- name: copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ root }}/docker-compose.yml"
    owner: root
    group: root
    mode: "644"
  notify: restart uptimekuma.service

- name: start uptimekuma.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: uptimekuma.service
  register: uptimekuma_started

