- name: Copy templates
  ansible.builtin.import_tasks: copy-all-templates.yml
  vars:
    directory: ../templates
    notify_handlers: restart traefik.service

- name: Create docker network web
  docker_network:
    name: web

- name: start traefik.service
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    enabled: true
    name: traefik.service
  register: traefik_started
