- name: restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
  async: 120
  poll: 0
  register: net_restarting

- name: check restart systemd-networkd status
  async_status:
    jid: "{{ net_restarting.ansible_job_id }}"
  register: async_poll_results
  until: async_poll_results.finished
  retries: 30
  listen: restart systemd-networkd
